language: cpp
sudo: false
cache: cargo

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    - source $HOME/.cargo/env

script:
    - make CXX="g++-7 -std=c++14"
    - cd tm-compression-rs && cargo test